folders:
  dev:
    path: '<%= ENV["USERPROFILE"] %>\Documents\Dev'
    sub_folders: ['Heroku', 'Node', 'Python', 'Ruby', 'Test']
  node:
    path: '<%= ENV["USERPROFILE"] %>\Documents\Dev\Node'
    sub_folders: ['CoffeeScript', 'Test']
  python:
    path: '<%= ENV["USERPROFILE"] %>\Documents\Dev\Python'
    sub_folders: ['Test']
  ruby:
    path: '<%= ENV["USERPROFILE"] %>\Documents\Dev\Ruby'
    sub_folders: ['Apps', 'Rails', 'Selenium', 'Sinatra', 'Test']

files:
  macinit:
    filename: 'macinit'
    path: '<%= ENV["SYSTEMDRIVE"] %>\tmp'
    content: ['alias=doskey /macros', 'dkey=subl C:\tmp\macinit', 'toDesk=cd %USERPROFILE%\Desktop$tcd', 'toDev=cd %USERPROFILE%\Documents\Dev$tcd', 'toNotes=cd %USERPROFILE%\Documents\Notes$tcd', 'toSinatra=cd %USERPROFILE%\Documents\Dev\Ruby\Sinatra$tcd', 'toRuby=cd %USERPROFILE%\Documents\Dev\Ruby$tcd', 'toCoffee=cd %USERPROFILE%\Documents\Dev\Node\CoffeeScript$tcd', 'simpleServer=python -m SimpleHTTPServer $1', 'localserver=ruby -run -e httpd . -p $1', 'mc=md $1$tcd $1$tcd', 'rd=rmdir /s /q $1', 'rm=del $1', 'mv=move $1 $2', 'l=dir $1 $2']
  myRun.bat:
    filename: 'myRun.bat'
    path: '<%= ENV["SYSTEMDRIVE"] %>\tmp'
    content: ['@echo off', 'prompt $n:$g', 'doskey /macrofile=C:\tmp\macinit', '@echo on']
  sudo:
    filename: 'sudo.cmd'
    path: 'C:\tools'
    content: ['@echo Set objShell = CreateObject("Shell.Application") > %temp%\sudo.tmp.vbs', '@echo args = Right("%*", (Len("%*") - Len("%1"))) >> %temp%\sudo.tmp.vbs', '@echo objShell.ShellExecute "%1", args, "", "runas" >> %temp%\sudo.tmp.vbs', '@cscript %temp%\sudo.tmp.vbs']

registry:
  editor:
    base: 'HKEY_LOCAL_MACHINE'
    location: 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
    key: 'EDITOR'
    value: 'C:\Program Files\Sublime Text 3\subl.bat'
  autorun:
    base: 'HKEY_CURRENT_USER'
    location: 'Software\Microsoft\Command Processor'
    key: 'Autorun'
    value: 'C:\tmp\myRun.bat'
